
services:
  db:
    image: postgres:latest
    restart: always
    env_file:
      - .env
    volumes:
      - pgdata:/var/lib/postgresql/data
      - ~/postgres_config/pg_hba.conf:/var/lib/postgresql/data/pg_hba.conf
    ports:
      - "5432:5432"
    command: ["postgres", "-c", "hba_file=/var/lib/postgresql/data/pg_hba.conf"]

  web:
    build: .
    depends_on:
      - db
    environment:
      DATABASE_URL: postgresql://admin:mypassword@db:5432/flask_db
    ports:
      - "5000:5000"

volumes:
  pgdata:
