name: Terraform Deployment

on:
  push:
    branches:
      - main

jobs:
  terraform:
    name: Deploy DigitalOcean Droplet
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: latest

      - name: Init Terraform
        run: terraform init
        working-directory: terraform

      - name: validate terraform
        run: terraform validate
        working-directory: terraform

      - name: Plan terraform
        env:
          TF_VAR_do_token: ${{ secrets.TOKEN }}
          TF_VAR_ssh_fingerprint: ${{ secrets.SSH }}
          S3_ACCESS_KEY: ${{ secrets.ACCESS_KEY_ID }}
          S3_SECRET_KEY: ${{ secrets.ACCESS_KEY_SECRET }}
        run: terraform apply -auto-approve
        working-directory: terraform

      - name: Show droplet IP
        run: terraform output droplet_ip
